### ISSUE TITLE
Add option for key mapping

### ISSUE THREAD

**Issue by drahnr** [reujab/silver#11]
As with most zsh themes, arrow up, insert, home, end, pos1 are not mapped.

Adding a switch to the eval subcommand would be awesome to autogenerate the expected key mappings.

**Comment by reujab** [comment]
I don't understand what you mean. Couldn't you use oh-my-zsh or something to map those keys?

**Comment by drahnr** [comment]
Yes, I could, but optimally this would just fall out of silver or is this out of scope?

**Comment by reujab** [comment]
Mapping keys seems out of scope for a prompt unless it can't be done with a framework like oh-my-zsh. I use oh-my-zsh with silver every day, and I feel it's more appropriate to have the keybindings (and every other sane default oh-my-zsh provides) handled by the framework.
