### ISSUE TITLE
unable to set separator

### ISSUE THREAD

**Issue by benbooth493** [reujab/silver#2]
I have this `~/.zshrc` configuration but no value for `SILVER_SEPARATOR` appears to do anything:

```
SILVER=(os:white:blue dir:blue:black git:red:black)
SILVER_SEPARATOR="\ue0b8"

export SILVER_SHELL="zsh"
eval "$(silver init)"
```

Any ideas?

**Comment by reujab** [comment]
The `SILVER_SEPARATOR` variable is not being exported, so silver is unable to access the variable. To achieve the expected result, replace that line with `export SILVER_SEPARATOR=$'\ue0b8'`. Thank you for reporting this; I will clarify this in the documentation.
