### ISSUE TITLE
Can't compile on macOS 10.14.6

### ISSUE THREAD

**Issue by ricardoinacio** [reujab/silver#20]
Couldn't compile silver to run on my mac, since I'd rather not install homebrew. Attached is the errors print.

[silver-compile-errors.txt](https://github.com/reujab/silver/files/3649351/silver-compile-errors.txt)

Environment:
```
Darwin Malayo.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
rustup 1.19.0 (2af131cf9 2019-09-08)
cargo 1.37.0 (9edd08916 2019-08-02)
rustc 1.37.0 (eae3437df 2019-08-13)
```

**Comment by hermitmaster** [comment]
You don’t need to compile, you should be able to just install it with cargo.

**Comment by reujab** [comment]
If you don't want to install Homebrew, you'll have to find a way to install GNU date and openssl manually before trying to install sivler.
