### ISSUE TITLE
Add RPROMPT support

### ISSUE THREAD

**Issue by ghost** [reujab/silver#23]
Add RPROMPT support for shells that support it (zsh, fish).

**Comment by reujab** [comment]
I don't personally use RPROMPT, so I wouldn't know how those who do would like it to be implemented. If you can explain how you would use such a feature, I'd be more than happy to implement it.

**Comment by deathtrip** [comment]
+1 for RPROMPT support from me.
I don't think there's much to be explained. It's just the possibility to place the modules you choose on the right side instead of the left.

**Comment by ghost** [comment]
As @deathtrip stated. The ability to use the same modules, just on the right instead of the left. Would also require reversing the direction of the separators.

**Comment by ghost** [comment]
If I can find some time in the near future, I’ll have a go at adding this for zsh.

**Comment by MinerChAI** [comment]
There’s an example on romkatv/powerlevel10k
