### ISSUE TITLE
Which font from nerd-fonts is needed?

### ISSUE THREAD

**Issue by iilyak** [reujab/silver#3]
I tried couple and they don't seem to work. The ones I tried:
- Droid Sans Mono Nerd Font
- Anonymice Nerd Font

**Comment by reujab** [comment]
When you say they don't work, do you mean that the glyphs don't render? Are you sure that your terminal is set to the correct font? Can you send a screenshot of your terminal prompt?

**Comment by iilyak** [comment]
Here is what I get

silver is installed inside docker container:
<img width="1313" alt="screen shot 2018-12-19 at 2 44 38 am" src="https://user-images.githubusercontent.com/9804420/50215581-4e67fb00-0338-11e9-858a-bbe2abf01f49.png">

Settings in iTerm2 are:
<img width="482" alt="screen shot 2018-12-19 at 2 45 04 am" src="https://user-images.githubusercontent.com/9804420/50215585-51fb8200-0338-11e9-9c36-0a27c7cf1adc.png">


P.S. Thank you for looking into it.

**Comment by iilyak** [comment]
Not sure if it would help but here is some debugging:
```
export SILVER=(status:black:white dir:blue:black git:
export SILVER_SHELL=bash
silver print "${SILVER[@]}" | hexdump
0000000 5b5c 5b1b 3434 5c6d 5c5d 1b5b 335b 6d30
0000010 5d5c ef20 9580 732f 6372 632f 756f 6863
0000020 6264 5c20 1b5b 345b 6d33 5d5c 5b5c 5b1b
0000030 3433 5c6d ee5d b082 5b5c 5b1b 3334 5c6d
0000040 5c5d 1b5b 335b 6d30 5d5c ee20 a082 ef20
0000050 9c80 80ef ef9c 9c80 80ef ef9c 9c80 80ef
0000060 209c 4548 4441 ef20 9184 5c20 1b5b 305b
0000070 5c6d 5c5d 1b5b 335b 6d33 5d5c 82ee 5cb0
0000080 1b5b 305b 5c6d 005d
0000087
```

**Comment by iilyak** [comment]
I am quite confident that silver is correct. It is just the matter of choosing the right font.

**Comment by reujab** [comment]
What happens when you use this font?

[Fura Code.zip](https://github.com/reujab/silver/files/2704012/Fura.Code.zip)

**Comment by iilyak** [comment]
It look almost the same. The difference only in the characters glyph and the fact that this one is mono spaced font.

**Comment by iilyak** [comment]
Not sure if it matter. My locale settings are different on the host and inside docker:
In docker I have:
```
locale
LANG=en_GB.UTF-8
LANGUAGE=
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
```
On host I have:
```
locale
LANG="en_CA.UTF-8"
LC_COLLATE="en_CA.UTF-8"
LC_CTYPE="en_CA.UTF-8"
LC_MESSAGES="en_CA.UTF-8"
LC_MONETARY="en_CA.UTF-8"
LC_NUMERIC="en_CA.UTF-8"
LC_TIME="en_CA.UTF-8"
LC_ALL=
```

**Comment by iilyak** [comment]
Some more info. I noticed that prompt is actually working when I am in the nested git project.
<img width="698" alt="screen shot 2018-12-28 at 4 44 20 am" src="https://user-images.githubusercontent.com/9804420/50515743-4b1cef80-0a5b-11e9-910a-63221606ce05.png">

the structure of the project is:
```
<main_repository>
   |- src/<showroom_repository>
```

The prompt is displayed correctly when I am inside `src/showroom` directory.
It is not displayed correctly when I am in the root of the project.

**Comment by reujab** [comment]
I don't see an issue with that last screenshot you posted; the glyphs appear to be properly rendered. Is the issue all of those git stash icons?

If the issue you're having *is* with the glyphs, what happens when you use another terminal for macOS?

**Comment by iilyak** [comment]
There is a big number of 
![image](https://user-images.githubusercontent.com/9804420/50591706-c7417980-0e45-11e9-819e-a22543daa979.png)

These icons take 1/4 of my screen. Given the fact that for some unrelated reason docker cannot use whole width of my terminal (but only half of it), most of the commands I type end up to be splited into multiple lines. Which is hard to read.

Anyway it seems like another issue. Fura Code.zip fixes the issue with glyphs. Thank you for your help.
