### ISSUE TITLE
Time to cut a new release?

### ISSUE THREAD

**Issue by ghost** [reujab/silver#35]
There have been a number of fixes and features added since the last release. It would be nice to get the latest from Fedora repos. :) The git icon for ssh repos is working btw. Thanks again!

**Comment by korochun** [comment]
Please do update ASAP, as the crate on crates.io is hella outdated and doesn't work with the fish plugin.

**Comment by magistau** [comment]
Soon:tm:

**Comment by appelgriebsch** [comment]
Any idea when you will release a new version? Especially the issue with long lines is annoying....

**Comment by appelgriebsch** [comment]
Awesome, thanks!

**Comment by erikbrinkman** [comment]
ping again here, after #87, you can build silver via git, but not crates.io. All it would take a patch release, and there's no other commits between this and the 2.0.0 release
