### ISSUE TITLE
Modules not showing up

### ISSUE THREAD

**Issue by MGlolenstine** [reujab/silver#41]
After installing silver using `cargo install silver` on my Arch machine and editing of the `.zshrc` file, I'm met with this:
```
$(build_left_prompt)                                                                       $(build_right_prompt)
$reset_color
```
Now I'm not sure what went wrong if anything, but I'm slightly lost.

My `.zshrc`:

```Bash

export SILVER=(status:black:white dir:blue:black git:green:black cmdtime:magenta:black)
export SILVER_SHELL=zsh
source <(silver init)
setxkbmap si
setxkbmap -option kpdl:dot
export QT_QPA_PLUGIN="xcb"
export QT_QPA_PLATFORMTHEME="qt5ct"
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk/
unsetopt share_history
export PATH="/home/arch/.cargo/bin:"$PATH
export PATH="/home/arch/.local/bin:"$PATH
```

I'm using Konsole as the terminal application.

**Comment by magistau** [comment]
Try installing git version with `cargo install --git https://github.com/reujab/silver.git`

**Comment by MGlolenstine** [comment]
@MinerChAI Sadly no change.

**Comment by magistau** [comment]
Does the problem persist if you restart Konsole?

**Comment by MGlolenstine** [comment]
It does. Let me try it out with another terminal.

**Comment by MGlolenstine** [comment]
![image](https://user-images.githubusercontent.com/9406770/88369850-2d2b8400-cd91-11ea-92c0-13bcfc742743.png)
Tried it with 4 different terminals, but result is the same.
- XTerm
- Konsole
- Alacritty
- Gnome terminal

**Comment by magistau** [comment]
What is your zsh version?

**Comment by MGlolenstine** [comment]
Running `zsh --version` returns 
`zsh 5.8 (x86_64-pc-linux-gnu)`

**Comment by magistau** [comment]
Do other prompts like p10k work for you?

**Comment by MGlolenstine** [comment]
If I comment out "SILVER" lines in the .zshrc, the p9k works fine.

# EDIT
I've also disabled `oh-my-zsh` to see if that would be causing it, but it's not.

**Comment by MGlolenstine** [comment]
Ok, this was my bad. For some reason Konsole doesn't get rid of ENV variables even after restarting it.
I've opened Termite, disabled Oh-My-ZSH and now it works flawlessly.

Thanks for your help!
