### ISSUE TITLE
lprint and rprint are empty

### ISSUE THREAD

**Issue by luisdralves** [reujab/silver#59]
After installing through `cargo install --git https://github.com/reujab/silver.git` on fish/macos, the resulting prompt is empty. Here's what it looks like to me:

![prompt](https://i.ibb.co/MpC5DDv/Screenshot-2020-09-24-at-10-45-42-AM.png)

I used the fisher plugin and I have the default config in ~/.config/silver/silver.toml

**Comment by magistau** [comment]
`~/.config/silver/silver.toml` is Linux path, on MacOS it's `~/Library/Preferences/rs.silver/silver.toml`

**Comment by luisdralves** [comment]
Looking great, thank you!
