### ISSUE TITLE
prompt does not display correctly in elvish

### ISSUE THREAD

**Issue by deathtrip** [reujab/silver#60]
I added silver to elvish, and i get something like this displayed:
`^[[47m^[[34m  ^[[44m^[[37m^[[44m^[[30m deathtrip@deathtripPC ^[[42m^[[34m^[[42m^[[30m  ^[[0m^[[32m^[[0m`
However `silver lprint` and `silver rprint` display the prompt correctly.

**Comment by magistau** [comment]
> I added silver to elvish, and i get something like this displayed:
> 
> `^[[47m^[[34m  ^[[44m^[[37m^[[44m^[[30m deathtrip@deathtripPC ^[[42m^[[34m^[[42m^[[30m  ^[[0m^[[32m^[[0m`
> 
> However `silver lprint` and `silver rprint` display the prompt correctly.

Update your elvish, it was fixed a while ago. Compiling elvish from source will definitely work.
