### ISSUE TITLE
Where am I supposed to put the silver.toml file?

### ISSUE THREAD

**Issue by eclipseo** [reujab/silver#73]
I can't seem to find a correct path, I've tried ~ and ~/.config with no success.
Thanks.

**Comment by magistau** [comment]
On Linux it's `~/.config/silver/silver.toml` or `$XDG_CONFIG_HOME/silver/silver.toml`

**Comment by amomchilov** [comment]
@j0hnmeow Coudl you please edit that into the homepage? I see that it's mentioned in the wiki, but it seems important enough (IMO) to mention up front on the README.

Also, what's the compatibility like between the TOML config file and the Fish shell? It looks to me like the new `silver` fisher plugin wasn't made to use the config file, is that correct?

**Comment by amomchilov** [comment]
@j0hnmeow Actually is looks with confy v0.4.0, the expected path is `~/Library/Preferences/rs.silver/silver.toml`

**Comment by magistau** [comment]
> Also, what's the compatibility like between the TOML config file and the Fish shell? It looks to me like the new `silver` fisher plugin wasn't made to use the config file, is that correct?

Well, it doesn't currently support custom config path

**Comment by amomchilov** [comment]
> @j0hnmeow Coudl you please edit that into the homepage? I see that it's mentioned in the wiki, but it seems important enough (IMO) to mention up front on the README.
> 
> Also, what's the compatibility like between the TOML config file and the Fish shell? It looks to me like the new `silver` fisher plugin wasn't made to use the config file, is that correct?

@j0hnmeow  Just in case you missed this ^

**Comment by eclipseo** [comment]
Well I know what it wasn't working, I was still on 1.1.0. Maintainer is lazy.
