### ISSUE TITLE
Doesn't work with fish after upgrading to 2.0.0

### ISSUE THREAD

**Issue by ilya-fedin** [reujab/silver#83]
I just updated silver to 2.0.0, checked the wiki for actual instructions, replaced `eval (silver init)` with `silver init | source` and started a new shell instance, but I got this message:
```
thread 'main' panicked at 'unknown shell: "fish". Supported shells: bash, ion, powershell', src/main.rs:69:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
:(

**Comment by magistau** [comment]
fish support was moved to a separate fish [plugin](https://github.com/silver-prompt/fish), use that instead

**Comment by ilya-fedin** [comment]
What if I don't want to use fisher?

**Comment by magistau** [comment]
You can copy the required files manually

**Comment by ilya-fedin** [comment]
Thx, works just fine, just copied the content of silver.fish to my config.fish
